### ISSUE TITLE
Error when building docker 

### ISSUE THREAD

**Issue by wentaoxandry** [espnet/espnet#1619]
When I building docker, I run espnet/docker/build.sh: sudo ./build.sh local 10.0, but I got this error:

. venv/bin/activate && pip install cupy-cuda==6.0.0

ERROR: Could not find a version that satisfies the requirement cupy-cuda==6.0.0 (from versions: none)
ERROR: No matching distribution found for cupy-cuda==6.0.0
Makefile:77: recipe for target 'cupy.done' failed
make: *** [cupy.done] Error 1
The command '/bin/sh -c if [ -z "$( nvcc -V )" ]; then         make KALDI=/kaldi CUPY_VERSION='';     else         sed -i '161s|install.py|install.py --no-cupy|' Makefile &&         sed -i '21s|nvidia-smi|nvcc|' Makefile &&         make KALDI=/kaldi CUDA_VERSION=${CUDA_VER};     fi' returned a non-zero code: 2

I have installed espnet with no error but I don't know why I got this Error by building docker.
Please help me and tell me how can I fix it.
Thank you

**Comment by Fhrozen** [comment]
I am testing this. I hope to solve soon. No ETC.

**Comment by Arafat4341** [comment]
I want to run docker in t2.micro ec2 instance of aws. I don't have GPU.
`./run.sh --docker_gpu 0 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 1`
is this command okay for me to work?

**Comment by Fhrozen** [comment]
@Arafat4341, For not GPU should be `./run.sh --docker_gpu -1 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --dlayers 1 --ngpu 0 `

**Comment by Arafat4341** [comment]
@Fhrozen Thank you so much! Lets try!

**Comment by Arafat4341** [comment]
`useradd: UID 0 is not unique`
I get this after completing pulling.

**Comment by Fhrozen** [comment]
Are you executing `run.sh` as Root?, which is the ID=0. IF that is the case then use `./run.sh docker_user false ...`

**Comment by Arafat4341** [comment]
I used `sudo` . 
After adding `--docker_user false` I get `./run.sh: invalid option --dlayers`

`Using image espnet/espnet:cpu-u18.
Executing application in Docker
docker run -i --rm --name espnet_cpu_20200310T0958 -v /home/ubuntu/espnet/espnet/egs:/espnet/                                                                           egs -v /home/ubuntu/espnet/espnet/espnet:/espnet/espnet -v /home/ubuntu/espnet/espnet/test:/e                                                                           spnet/test -v /home/ubuntu/espnet/espnet/utils:/espnet/utils -v /export/corpora4/CHiME4/CHiME                                                                           3:/export/corpora4/CHiME4/CHiME3 espnet/espnet:cpu-u18 /bin/bash -c 'cd /espnet/egs/chime4/as                                                                           r1; ./run.sh --dlayers 1 --ngpu 0; chmod -R 777 /espnet/egs/chime4/asr1'
./run.sh: invalid option --dlayers
run.sh done.
`

**Comment by Fhrozen** [comment]
Sorry I forgot to tell you that the problem is that `--dlayers` is no longer accepted in recipe `run.sh`. For this, you will need to write a new `train_config` file in `conf` folder and call it with:
```
./run.sh --docker_gpu -1 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --docker_user false --train_config conf/<my_train_file>.yaml --ngpu 0
```
You can use [this file](https://github.com/espnet/espnet/blob/master/egs/chime4/asr1/conf/tuning/train_pytorch_transformer.yaml) as reference.

**Comment by Arafat4341** [comment]
Can't I directly use `train_pytorch_transformer.yaml` ?
If not then which part to edit?! Can kindly tell?!

**Comment by Fhrozen** [comment]
`train_pytorch_transformer.yaml` is the default config file used for training: https://github.com/espnet/espnet/blob/9e2bfc5cdecbb8846f5c6cb26d22010b06e98c40/egs/chime4/asr1/conf/train.yaml#L1

https://github.com/espnet/espnet/blob/9e2bfc5cdecbb8846f5c6cb26d22010b06e98c40/egs/chime4/asr1/run.sh#L23

so you do not need to any additional modification.
```
./run.sh --docker_gpu -1 --docker_egs chime4/asr1 --docker_folders /export/corpora4/CHiME4/CHiME3 --docker_user false  --ngpu 0
```
In case that you want to train your self defined model, then you will need to prepare a new yaml file.

**Comment by Arafat4341** [comment]
Okay! 
But I am getting `find: '/export/corpora4/CHiME4/CHiME3/data/WSJ0': No such file or directory`

**Comment by Fhrozen** [comment]
well, that depends on your system. For CHiME 4, you will need to download the data from the official page: http://spandh.dcs.shef.ac.uk/chime_challenge/CHiME3/. http://spandh.dcs.shef.ac.uk/chime_challenge/CHiME4/.
 Then, save it in you local dir and add this to the run command, such as:
```
./run.sh --docker_gpu -1 --docker_egs chime4/asr1 --docker_folders /<my_dir>/CHiME4/CHiME3;/<mydir>/LDC/LDC93S6B;/<my_dir>/LDC/LDC94S13B  --docker_user false  --ngpu 0 --chime4_data /<my_dir>/CHiME4/CHiME3 --wsj0 /<mydir>/LDC/LDC93S6B --wsj1 /<my_dir>/LDC/LDC94S13B
```

In case that you do not have access to WSJ then I will recommend you try another recipe, such as librispeech or voxforge. This last is smaller so it will be faster to train in CPU. For testing, then I recommend you to use AN4. THis will take 20 mins to train in CPU.

```
./run.sh --docker_gpu -1 --docker_egs an4/asr1   --docker_user false  --ngpu 0
```

**Comment by Arafat4341** [comment]
I ran `./run.sh --docker_gpu -1 --docker_egs an4/asr1   --docker_user false  --ngpu 0` .
Now I get:
`run.pl: job failed, log is in exp/train_nodev_pytorch_train_mtlalpha1.0/train.log`

**Comment by sw005320** [comment]
@Arafat4341, could you read our documentation carefully? Some of the answers to your questions can be found there. It would be great if you put questions related to this issue.

**Comment by Arafat4341** [comment]
@sw005320 well, firstly I worked according to the documentation. Things were not working properly that's why I asked questions here! Still facing errors! I am sorry for your troubles!

**Comment by chris-crucible** [comment]
Any update here on the original posted issue? I'm also getting the error ``No matching distribution found for cupy-cuda==6.0.0`` when running ``./build.sh local 10.0`` on AWS EC2 instance.

**Comment by sw005320** [comment]
@chris-crucible, we just merged it today. Could you check it?

**Comment by chris-crucible** [comment]
I updated to latest master and still receive the same error. Seems like line 82 in tools/Makefile is resolving to ``cupy-cuda==6.0.0`` instead of ``cupy-cuda100==6.0.0``. I tried manually editing the Makefile to force it to that, but changes the Makefile seem to have no effect. Is there some cached version of it? What is the correct way to change it?

**Comment by sw005320** [comment]
> I updated to latest master and still receive the same error. Seems like line 82 in tools/Makefile is resolving to `cupy-cuda==6.0.0` instead of `cupy-cuda100==6.0.0`. I tried manually editing the Makefile to force it to that, but changes the Makefile seem to have no effect. Is there some cached version of it? What is the correct way to change it?

@Fhrozen, could you check it?

**Comment by Fhrozen** [comment]
@chris-crucible Thank you for your report.
PR #1677 solves the problems you mentioned.
