### ISSUE TITLE
Error 404 - tedlium transformers checkpoints - Google Drive

### ISSUE THREAD

**Issue by GokulNC** [espnet/espnet#2029]
The following 2 links from the [ASR Demo](https://github.com/espnet/espnet#asr-demo) are broken:

- [tedlium2.transformer.v1](https://drive.google.com/open?id=1mgbiWabOSkh_oHJIDA-h7hekQ3W95Z_U)
- [tedlium3.transformer.v1](https://drive.google.com/open?id=1wYYTwgvbB7uy6agHywhQfnuVWWW_obmO)

Please re-up :)

**Comment by GokulNC** [comment]
@sw005320 

I pulled the latest and rebuilt espnet, and then tried the above 2 models:

```
(base) 1 jupyter@gokulnc:~/Speech/espnet/egs/tedlium2/asr1$ recog_wav.sh --models tedlium2.transformer.v1 ~/Speech/example.wav
No such config file:
(base) 1 jupyter@gokulnc:~/Speech/espnet/egs/tedlium2/asr1$ recog_wav.sh --models tedlium3.transformer.v1 ~/Speech/example.wav
--2020-06-13 05:05:11--  https://drive.google.com/uc?export=download&id=1ESVWQp0ZMhenF_Dt1n47suMK8NJ8hm0A
Resolving drive.google.com (drive.google.com)... 74.125.20.138, 74.125.20.100, 74.125.20.113, ...
Connecting to drive.google.com (drive.google.com)|74.125.20.138|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'decode/download/tedlium3.transformer.v1/wbmrIX..tar.gz'

decode/download/tedlium3.transformer.v1/wbmrIX..     [ <=>                                                                                                       ]   3.19K  --.-KB/s    in 0s

2020-06-13 05:05:11 (29.3 MB/s) - 'decode/download/tedlium3.transformer.v1/wbmrIX..tar.gz' saved [3265]


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3265    0  3265    0     0  16983      0 --:--:-- --:--:-- --:--:-- 17005
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0   2229      0 --:--:-- --:--:-- --:--:--  2229
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  230M    0  230M    0     0  66.0M      0 --:--:--  0:00:03 --:--:--  102M
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Any idea?

**Comment by sw005320** [comment]
It seems to come from the zip and tgz file difference.
The file was saved as a zip file while `recog_wav.sh` assumes `tar.gz` files in 
https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh#L142
I think you can fix it by modifying this line (simple removing the third argument?)

@takenori-y, `download_from_google_drive.sh` can flexibly use zip or tgz files. Is it possible to modify `recog_wav.sh` according to that?

**Comment by takenori-y** [comment]
I fixed it. Is it OK?

**Comment by sw005320** [comment]
Many thanks!
@GokulNC, could you test it?

**Comment by GokulNC** [comment]
@sw005320 

For the tedlium2 checkpoint, the error still persists:
```
(base) 1 jupyter@gokulnc:~/Speech/espnet/egs/tedlium2/asr1$ recog_wav.sh --models tedlium2.transformer.v1 ~/Speech/example.wav
No such config file:
```
(Though the model was downloaded and unzipped successfully)

For the tedlium3 checkpoint, download and extraction works. But:
```
(base) 1 jupyter@gokulnc:~/Speech/espnet/egs/tedlium3/asr1$ recog_wav.sh --models tedlium3.transformer.v1 ~/Speech/example.wav
stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 1 --write_utt2num_frames true decode/example/data decode/example/log decode/example/fbank
steps/make_fbank_pitch.sh: moving decode/example/data/feats.scp to decode/example/data/.backup
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory decode/example/data
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_fbank_pitch.sh: Succeeded creating filterbank and pitch features for data
/home/jupyter/Speech/espnet/egs/tedlium3/asr1/../../../utils/dump.sh --cmd run.pl --nj 1 --do_delta false decode/example/data/feats.scp decode/download/tedlium3.transformer.v1/tedlium3.transformer.v1/data/train_trim_sp/cmvn.ark decode/example/log decode/example/dump
stage 2: Json Data Preparation
/home/jupyter/Speech/espnet/egs/tedlium3/asr1/../../../utils/data2json.sh --feat decode/example/dump/feats.scp decode/example/data decode/example/dict
/home/jupyter/Speech/espnet/egs/tedlium3/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 decode/example/dump/feats.scp decode/example/data/tmp-66HZi/input_1/shape.scp
sym2int.pl: replacing X with 1
** Replaced 1 instances of OOVs with 1
stage 3: Decoding
run.pl: job failed, log is in decode/example/log/decode.log
```

Contents of `decode/example/log/decode.log`:
```
(base) jupyter@gokulnc:~/Speech/espnet/egs/tedlium3/asr1$ cat decode/example/log/decode.log
# asr_recog.py --config decode/download/tedlium3.transformer.v1/tedlium3.transformer.v1/conf/decode_pytorch_transformer_beam-size40.yaml --ngpu 0 --backend pytorch --debugmode 1 --verbose 1 --recog-json decode/example/dump/data.json --result-label decode/example/result.json --model decode/download/tedlium3.transformer.v1/tedlium3.transformer.v1/exp/train_trim_sp_pytorch_nbpe500_ngpu8_train_pytorch_transformer.v2_specaug/results/model.last10.avg.best --api v2 --rnnlm decode/download/tedlium3.transformer.v1/tedlium3.transformer.v1/exp/train_rnnlm_pytorch_lm_irie_unit1024_unigram500/rnnlm.model.best
# Started at Tue Jun 16 08:19:17 UTC 2020
#
usage: asr_recog.py [-h] [--config CONFIG] [--config2 CONFIG2]
                    [--config3 CONFIG3] [--ngpu NGPU]
                    [--dtype {float16,float32,float64}]
                    [--backend {chainer,pytorch}] [--debugmode DEBUGMODE]
                    [--seed SEED] [--verbose VERBOSE] [--batchsize BATCHSIZE]
                    [--preprocess-conf PREPROCESS_CONF] [--api {v1,v2}]
                    [--recog-json RECOG_JSON] --result-label RESULT_LABEL
                    --model MODEL [--model-conf MODEL_CONF]
                    [--num-spkrs {1,2}] [--num-encs NUM_ENCS] [--nbest NBEST]
                    [--beam-size BEAM_SIZE] [--penalty PENALTY]
                    [--maxlenratio MAXLENRATIO] [--minlenratio MINLENRATIO]
                    [--ctc-weight CTC_WEIGHT]
                    [--weights-ctc-dec WEIGHTS_CTC_DEC]
                    [--ctc-window-margin CTC_WINDOW_MARGIN]
                    [--score-norm-transducer [SCORE_NORM_TRANSDUCER]]
                    [--rnnlm RNNLM] [--rnnlm-conf RNNLM_CONF]
                    [--word-rnnlm WORD_RNNLM]
                    [--word-rnnlm-conf WORD_RNNLM_CONF]
                    [--word-dict WORD_DICT] [--lm-weight LM_WEIGHT]
                    [--ngram-model NGRAM_MODEL] [--ngram-weight NGRAM_WEIGHT]
                    [--ngram-scorer {full,part}]
                    [--streaming-mode {window,segment}]
                    [--streaming-window STREAMING_WINDOW]
                    [--streaming-min-blank-dur STREAMING_MIN_BLANK_DUR]
                    [--streaming-onset-margin STREAMING_ONSET_MARGIN]
                    [--streaming-offset-margin STREAMING_OFFSET_MARGIN]
asr_recog.py: error: unrecognized arguments: --mtlalpha=1.0
# Accounting: time=0 threads=1
# Ended (code 2) at Tue Jun 16 08:19:17 UTC 2020, elapsed time 0 seconds
```

**Comment by GokulNC** [comment]
For the csj.transformer.v1 checkpoint, I face the following:
```
stage 3: Decoding
run.pl: job failed, log is in decode/example/log/decode.log
```

```
(base) 1 jupyter@gokulnc:~/Speech/espnet/egs/tedlium3/asr1$ cat decode/example/log/decode.log
# asr_recog.py --config decode/download/csj.transformer.v1/conf/decode.yaml --ngpu 0 --backend pytorch --debugmode 1 --verbose 1 --recog-json decode/example/dump/data.json --result-label decode/example/result.json --model decode/download/csj.transformer.v1/exp/train_nodup_sp_pytorch_train/results/model.acc.best --api v2 --rnnlm decode/download/csj.transformer.v1/exp/train_rnnlm_pytorch_lm/rnnlm.model.best
# Started at Tue Jun 16 08:34:50 UTC 2020
#
2020-06-16 08:34:50,803 (asr_recog:253) INFO: python path = (None)
2020-06-16 08:34:50,803 (asr_recog:258) INFO: set random seed = 1
2020-06-16 08:34:50,803 (asr_recog:269) INFO: backend = pytorch
/home/jupyter/Speech/espnet/tools/venv/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
/home/jupyter/Speech/espnet/tools/venv/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
2020-06-16 08:34:52,272 (recog:34) WARNING: experimental API for custom LMs is selected by --api v2
2020-06-16 08:34:52,273 (deterministic_utils:26) INFO: torch type check is disabled
2020-06-16 08:34:52,273 (asr_utils:478) INFO: reading a config file from decode/download/csj.transformer.v1/exp/train_nodup_sp_pytorch_train/results/model.json
2020-06-16 08:34:52,273 (asr_init:169) WARNING: reading model parameters from decode/download/csj.transformer.v1/exp/train_nodup_sp_pytorch_train/results/model.acc.best
Traceback (most recent call last):
  File "/home/jupyter/Speech/espnet/egs/tedlium3/asr1/../../../espnet/bin/asr_recog.py", line 311, in <module>
    main(sys.argv[1:])
  File "/home/jupyter/Speech/espnet/egs/tedlium3/asr1/../../../espnet/bin/asr_recog.py", line 281, in main
    recog_v2(args)
  File "/home/jupyter/Speech/espnet/espnet/asr/pytorch_backend/recog.py", line 43, in recog_v2
    model, train_args = load_trained_model(args.model)
  File "/home/jupyter/Speech/espnet/espnet/asr/pytorch_backend/asr_init.py", line 176, in load_trained_model
    model = model_class(idim, odim, train_args)
  File "/home/jupyter/Speech/espnet/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 220, in __init__
    selfattention_layer_type=args.transformer_encoder_selfattn_layer_type,
AttributeError: 'Namespace' object has no attribute 'transformer_encoder_selfattn_layer_type'
# Accounting: time=2 threads=1
# Ended (code 1) at Tue Jun 16 08:34:52 UTC 2020, elapsed time 2 seconds
```
