### ISSUE TITLE
recog_wav.sh broken

### ISSUE THREAD

**Issue by Dicksonchin93** [espnet/espnet#2060]
I got this error in the latest master using recog_wav.sh

`AttributeError:` 'Namespace' object has no attribute 'transformer_encoder_selfattn_layer_type' `

checking out version v.0.7.0 solved the problem, but I thought I should report this bug

**Comment by kan-bayashi** [comment]
Fixed.

**Comment by sw005320** [comment]
> Fixed.

Many thanks, @kan-bayashi!

**Comment by jefflai108** [comment]
Hi, 

After doing `git pull origin master`, i am still getting the same error. What should I do to fix it? 
thanks!

**Comment by kan-bayashi** [comment]
I could not reproduce with the current master.
Could you share the snippet to reproduce your error?

**Comment by jefflai108** [comment]
hi @kan-bayashi 
Sorry, I solved the error. I didn't set up the environment correctly (I did `pip install espnet`).
