### ISSUE TITLE
The Bug in data preparation for How2 Summarization

### ISSUE THREAD

**Issue by teinhonglo** [espnet/espnet#4459]
**To Reproduce**
1. move to a recipe directory, e.g., `cd egs2/how2_2000h/summ1`
2. `local/run_asr.sh --asr_tag asr_pretrain`

**Error logs**
```
2022-06-19T15:12:30 (asr.sh:252:main) ./asr.sh --lang en --feats_type extracted --token_type bpe --nbpe 1000 --nlsyms_txt data/nlsyms --bpe_nlsyms [hes] --use_lm false --asr_config conf/train_asr_conformer_lf.yaml --inference_config conf/decode_asr.yaml --train_set tr_2000h_utt --valid_set cv05_utt --test_sets dev5_test_utt --bpe_train_text data/tr_2000h_utt/text --asr_tag asr_pretrain
2022-06-19T15:12:34 (asr.sh:443:main) Stage 1: Data preparation for data/tr_2000h_utt, data/cv05_utt, etc.
2022-06-19T15:12:38 (data.sh:23:main) local/data.sh
2022-06-19T15:12:42 (data.sh:36:main) stage 0: Data download
/home/teinhonglo/espnets/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/gdown/cli.py:127: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=sharing
```

Besides,
The link provided by [local/data.sh](https://github.com/espnet/espnet/blob/305e974e553ec0b36c74c2d8f52fc5fc06631e32/egs2/how2_2000h/sum1/local/data.sh#L20) is not available now.

Thanks in advnace.

**Comment by sw005320** [comment]
@roshansh-cmu, can you answer it for me?
Google drive downloading is tricky.
You may think of hosting it in the other storage (e.g., huggingface)

**Comment by roshansh-cmu** [comment]
Thank you for opening this issue. 

This issue might take se time to resolve due to server issues. I am investigating alternative storage and will respond here when the issue is resolved.

**Comment by roshansh-cmu** [comment]
Please request the dataset using the data release form from the How2 data repository : https://github.com/srvk/how2-dataset.

Apologies for the long delay in replying

**Comment by teinhonglo** [comment]
@roshansh-cmu 

Thanks for your reply.
The problem above is solved, but I encountered a runtime error as below.
Any ideas?

Thanks in advance.
Tien-Hong Lo
```
Traceback (most recent call last):
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/tools/anaconda/envs/espnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/espnet2/tasks/abs_task.py", line 1315, in main_worker
    cls.trainer.run(
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/espnet2/train/trainer.py", line 282, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/espnet2/train/trainer.py", line 556, in train_one_epoch
    retval = model(**batch)
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/espnet2/asr/espnet_model.py", line 202, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/share/nas165/teinhonglo/espnets/espnet-20220922/espnet2/asr/espnet_model.py", line 368, in encode
    assert encoder_out.size(1) <= encoder_out_lens.max(), (
AssertionError: (torch.Size([1, 3120, 512]), tensor(3036, device='cuda:0'))
Loading tvm binary from: /share/nas165/teinhonglo/espnets/espnet-20220922/tools/anaconda/envs/espnet/lib/python3.8/site-packages/longformer/../longformer/lib/lib_diagonaled_mm_float32_cuda.so
# Accounting: time=13 threads=1
```

**Comment by roshansh-cmu** [comment]
Please wait for a day- I am in the process of setting up a PR to fix this and other issues with the recipe. Thanks!

**Comment by roshansh-cmu** [comment]
You may refer to our PR https://github.com/espnet/espnet/pull/4805- this when merged should be used to prepare data from the downloaded dataset bz2 file. 
The modification made to espnet_model.py should fix the assertion error you are facing 

Thank you!

**Comment by smilepokemmo** [comment]
@teinhonglo Hello, thank you for your work! May I ask if you still have a backup of the How2_2000h dataset? The official sources no longer provide this dataset and suggest obtaining it from other downloaders. Unfortunately, the dataset I downloaded earlier is missing some files - specifically, I may be missing cv05utt, cv05_sum, utt2spk, and spk2utt. Additionally, could you provide the complete dataset structure? This will help me further confirm which parts are missing.

**Comment by teinhonglo** [comment]
Hello, thank you for your message!

I'm not the original author of the dataset, but I do still have the copy I downloaded back when it was available.

I just checked my local copy of the dataset.
For both the `cv05_sum` and `cv05utt` subsets, I have the following files in each folder:

```
[cv05_sum] and [cv05utt]/
├── feats_dim
├── feats_shape
├── feats_type
├── feats.scp
├── frame_shift
├── spk2utt
├── text
├── utt2dur
├── utt2spk
```

So it looks like I do have the `utt2spk`, `spk2utt`, as well as other relevant files you mentioned.
